name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish win-x64
      run: dotnet publish -r win-x64 --configuration Release /p:PublishSingleFile=true
    - name: Publish win-x86
      run: dotnet publish -r win-x86 --configuration Release /p:PublishSingleFile=true
    - name: Publish win-arm
      run: dotnet publish -r win-arm --configuration Release /p:PublishSingleFile=true
    - name: Publish osx-x64
      run: dotnet publish -r osx-x64 --configuration Release /p:PublishSingleFile=true
    - name: Publish linux-x64
      run: dotnet publish -r linux-x64 --configuration Release /p:PublishSingleFile=true
    - name: Publish linux-musl-x64
      run: dotnet publish -r linux-musl-x64 --configuration Release /p:PublishSingleFile=true
    - name: Publish linux-arm
      run: dotnet publish -r linux-arm --configuration Release /p:PublishSingleFile=true
    - name: Publish linux-arm64
      run: dotnet publish -r linux-arm64 --configuration Release /p:PublishSingleFile=true
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: server-${{ env.name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/src/DnsPush.Server/**/publish/*
    - name: Upload Console Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: console-${{ env.name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/src/DnsPush.Console/**/publish/*
